### ISSUE TITLE
ConvenientInventory - Case sensitive folder path causing errors

### ISSUE THREAD

**Issue by Lightsockie** [alanperrow/StardewModding#6]
```
[Convenient Inventory] Mod crashed on entry and might not work correctly. Technical details:
SContentLoadException: Failed loading asset 'Assets/icon.png' from SMAPI/gaussfire.convenientinventory: the specified path doesn't exist.
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.Load[T](String assetName, LanguageCode language, Boolean useCache)
   at StardewModdingAPI.Framework.ModHelpers.ContentHelper.Load[T](String key, ContentSource source)
   at ConvenientInventory.ModEntry.Entry(IModHelper helper)
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase)
```

ya needa either rename the "assets" folder to be "Assets", or correct the path in your source fam

Linux & macOS have case-sensitive files (think Windows doesn't?)

Mod loads fine when I fix it manually, just heads up for ya it's a problem

**Comment by alanperrow** [comment]
Hey, yeah apparently visual studio automatically lowercases directory folders when compiling, because I have it capitalized in my Dev environment, so I never noticed. 
I have this fixed in a separate branch, I just have to merge it and publish it on nexus mods. Thanks for the heads up.
